<?php return array (
  'sycog_id' => 1,
  'generalcus' => '{"cm_id":"0","customer":"Walk-In"}',
  'generalsplier' => '{"supplier_id":"1","supplier":"General Supplier"}',
  'pdfwatermask' => 'SWS',
  'pdfformat' => '{"format":["A4","A5","80,1440"],"orientation":["P","L","P"],"margin_left":["10","10","5"],"margin_right":["10","10","5"],"margin_top":["55","40","0"],"margin_bottom":["20","20","20"],"margin_header":["10","10","0"],"margin_footer":["10","10","10"]}',
  'usingsizecolor' => 'yes',
  'sub_input' => '1',
  'cus_level' => 0,
  'splier_level' => 0,
  'info_tag' => '{"invtheme":"t1","postheme":"t1","paymentinfo":"","pospmethod_id":"1","posaccno_id":"","acc_salediscount":"","poswelcometext":"Welcome to i-POS. A new modern System works online and more user friendly, Functional and Interface.","companyname":"Serving Web Solution","productnum":"-1","whnum":"2","branchnum":"2","posfor":"pos","catlabo":"","catimagery":"","catservice":""}',
  'yesnotag' => '{"p2ptransfer":"auto","madewithstock":"resource","usingextraprice":"no","df_dis":"1","ct_id":"0","costmethod":"fefo","lowstock":"6","requiredchkin":"yes","ciosize":"a4","cioproduct":"yes","restaurant":"no","withcosting":"no","customermode":"map","madewithtocart":"main","holdmode":"share"}',
  'herder_text' => '{"inv":"INV-","qt":"QT","pch":"PCH","po":"PO","dl":"DL","iddigit":"6","rp":"AR-","pp":"AP","exp":"EXP-","addstock":"ADD-","adjuststock":"ADJ-","je":"JE","rt":"RTN","rtpch":"RTN-PCH"}',
  'dctype' => 0,
  'syssetting' => '{"lang":["en","kh"]}',
  'blongto' => 1,
  'cm_id' => '0',
  'customer' => 'Walk-In',
  'supplier_id' => '1',
  'supplier' => 'General Supplier',
  'invtheme' => 't1',
  'postheme' => 't1',
  'paymentinfo' => '',
  'pospmethod_id' => '1',
  'posaccno_id' => '',
  'acc_salediscount' => '',
  'poswelcometext' => 'Welcome to i-POS. A new modern System works online and more user friendly, Functional and Interface.',
  'companyname' => 'Serving Web Solution',
  'productnum' => '-1',
  'whnum' => '2',
  'branchnum' => '2',
  'posfor' => 'pos',
  'catlabo' => '',
  'catimagery' => '',
  'catservice' => '',
  'p2ptransfer' => 'auto',
  'madewithstock' => 'resource',
  'usingextraprice' => 'no',
  'df_dis' => '1',
  'ct_id' => '0',
  'costmethod' => 'fefo',
  'lowstock' => '6',
  'requiredchkin' => 'yes',
  'ciosize' => 'a4',
  'cioproduct' => 'yes',
  'restaurant' => 'no',
  'withcosting' => 'no',
  'customermode' => 'map',
  'madewithtocart' => 'main',
  'holdmode' => 'share',
  'inv' => 'INV-',
  'qt' => 'QT',
  'pch' => 'PCH',
  'po' => 'PO',
  'dl' => 'DL',
  'iddigit' => '6',
  'rp' => 'AR-',
  'pp' => 'AP',
  'exp' => 'EXP-',
  'addstock' => 'ADD-',
  'adjuststock' => 'ADJ-',
  'je' => 'JE',
  'rt' => 'RTN',
  'rtpch' => 'RTN-PCH',
  'format' => 
  array (
    0 => 'A4',
    1 => 'A5',
    2 => '80,1440',
  ),
  'orientation' => 
  array (
    0 => 'P',
    1 => 'L',
    2 => 'P',
  ),
  'margin_left' => 
  array (
    0 => '10',
    1 => '10',
    2 => '5',
  ),
  'margin_right' => 
  array (
    0 => '10',
    1 => '10',
    2 => '5',
  ),
  'margin_top' => 
  array (
    0 => '55',
    1 => '40',
    2 => '0',
  ),
  'margin_bottom' => 
  array (
    0 => '20',
    1 => '20',
    2 => '20',
  ),
  'margin_header' => 
  array (
    0 => '10',
    1 => '10',
    2 => '0',
  ),
  'margin_footer' => 
  array (
    0 => '10',
    1 => '10',
    2 => '10',
  ),
  'pdfformat0' => 
  array (
    'format' => 'A4',
    'orientation' => 'P',
    'margin_left' => '10',
    'margin_right' => '10',
    'margin_top' => '55',
    'margin_bottom' => '20',
    'margin_header' => '10',
    'margin_footer' => '10',
  ),
  'pdfformat1' => 
  array (
    'format' => 'A5',
    'orientation' => 'L',
    'margin_left' => '10',
    'margin_right' => '10',
    'margin_top' => '40',
    'margin_bottom' => '20',
    'margin_header' => '10',
    'margin_footer' => '10',
  ),
  'pdfformat2' => 
  array (
    'format' => '80,1440',
    'orientation' => 'P',
    'margin_left' => '5',
    'margin_right' => '5',
    'margin_top' => '0',
    'margin_bottom' => '20',
    'margin_header' => '0',
    'margin_footer' => '10',
  ),
);